browser:
  browser_name: chrome
  headless: true
  attach_screenshot: true
  web_element_timeout: 10
environment:
  test_int:
    env_name: test_int
    app_url: https://demo.aspnetawesome.com/
    title: TesterSii
    active: true
  test_prod:
    env_name: test_prod
    app_url: https://demo.aspnetawesome.com/
    title: TesterSii
    active: false